services:
  web:
    build: .
    container_name: skillero-web
    restart: always
    ports:
      - "80:3000"  # Host port 80 -> Container port 3000
    env_file:
      - .env.local  # Load environment variables from .env
    command: ["bun", "run", "start"]

volumes:
  bun_cache:
    driver: local
